server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Todo el backend bajo un solo bloque
    location ~ ^/(api|auth|usuarios|centros|centro)(/.*)?$ {
        proxy_pass http://backend:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # React Router
    location / {
        try_files $uri $uri/ /index.html;
    }
}