server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass https://backend-production-f5bc.up.railway.app/api/;
        proxy_set_header Host backend-production-f5bc.up.railway.app;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /auth/ {
        proxy_pass https://backend-production-f5bc.up.railway.app;
        proxy_set_header Host backend-production-f5bc.up.railway.app;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /usuarios {
        proxy_pass https://backend-production-f5bc.up.railway.app;
        proxy_set_header Host backend-production-f5bc.up.railway.app;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ~ ^/centros(/.*)?$ {
        if ($request_uri ~* "^/centros/[0-9]+/admin") {
            rewrite ^ /index.html last;
        }
        proxy_pass https://backend-production-f5bc.up.railway.app;
        proxy_set_header Host backend-production-f5bc.up.railway.app;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /pacientes/ {
        proxy_pass https://backend-production-f5bc.up.railway.app;
        proxy_set_header Host backend-production-f5bc.up.railway.app;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}